export const GET_USER_COORDS_SUCCESS = 'GET_USER_COORDS_SUCCESS';
export const GET_USER_COORDS_ERROR = 'GET_USER_COORDS_ERROR';
export const SET_CUSTOM_COORDS = 'SET_CUSTOM_COORDS';
export const TOOLTIP_INIT = 'TOOLTIP_INIT';
