export const GET_DAILY_WEATHER_SUCCESS = 'GET_DAILY_WEATHER_SUCCESS';
export const GET_DAILY_WEATHER_ERROR = 'GET_DAILY_WEATHER_ERROR';
export const GET_FIVE_DAYS_WEATHER_SUCCESS = 'GET_FIVE_DAYS_WEATHER_SUCCESS';
export const GET_FIVE_DAYS_WEATHER_ERROR = 'GET_FIVE_DAYS_WEATHER_ERROR';
export const FIVE_DAYS_COMPONENT_TOGGLE = 'FIVE_DAYS_COMPONENT_TOGGLE';
